version: '3'
name: rust-complete
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-rust-complete
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 6500:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "postgres",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rust_app_no_api_network

volumes:
  postgres:


networks:
  rust_app_no_api_network:
